apiVersion: v1
kind: Service
metadata:
  labels:
    app: grocery-website
  name: grocery-website-service
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30053
  selector:
    app: grocery-website
  type: NodePort

