---
apiVersion: apps/v1
kind: Deployment
# Radwan Ahmed Ibrahiem      Test rebase and merge --> fast forward merge and recursive merge
# now checking recursive merge 
metadata:
  labels:
    app: grocery-website
  name: grocery-website
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-website
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grocery-website
    spec:
      containers:
      - image: radwanmaazon/grocery_flask_app:${BUILD_NUMBER}.0
        name: grocery-flask-app-mg8q5
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME