apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-ubuntu-slave
  name: jenkins-ubuntu-slave
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ubuntu-slave
  template:
    metadata:
      labels:
        app: jenkins-ubuntu-slave
    spec:
      nodeName: k8s-node-3
      containers:
      - image: radwanmaazon/jenkins-slave:ubuntu22
        name: radwan-jenkins-slave
        ports:
          - containerPort: 22
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock

      volumes: 
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-ubuntu-slave
  name: jenkins-ubuntu-slave-svc
  namespace: jenkins
spec:
  selector:
    app: jenkins-ubuntu-slave
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
