---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: "1Gi"
#  persistentVolumeReclaimPolicy: Delete
  nfs: 
    server: 192.168.1.150
    path: /jenkins/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-jenkins-pvc
  namespace: jenkins
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"